# Generated by Django 5.1.1 on 2024-09-09 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='название детали')),
                ('diameter', models.FloatField(verbose_name='диаметр')),
                ('weight', models.FloatField(verbose_name='масса изделия, кг')),
                ('accuracy_class', models.CharField(max_length=250, verbose_name='класс точности')),
                ('cost', models.FloatField(verbose_name='Стоимость, руб')),
                ('strength_class', models.FloatField(verbose_name='класс прочности')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_list', models.TextField(verbose_name='состав заказа')),
                ('cost', models.FloatField(verbose_name='Стоимость, руб')),
                ('weight', models.FloatField(verbose_name='масса заказа, кг')),
            ],
        ),
        migrations.CreateModel(
            name='Bolt',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parts_ordering.item')),
                ('length', models.FloatField(verbose_name='номинальная длина')),
                ('size', models.FloatField(verbose_name='размер под ключ, мм')),
            ],
            options={
                'verbose_name': 'болт',
                'verbose_name_plural': 'болты',
            },
            bases=('parts_ordering.item',),
        ),
        migrations.CreateModel(
            name='Nut',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parts_ordering.item')),
                ('size', models.FloatField(verbose_name='размер под ключ, мм')),
            ],
            options={
                'verbose_name': 'гайка',
                'verbose_name_plural': 'гайки',
            },
            bases=('parts_ordering.item',),
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parts_ordering.item')),
            ],
            options={
                'verbose_name': 'шайба',
                'verbose_name_plural': 'шайбы',
            },
            bases=('parts_ordering.item',),
        ),
        migrations.CreateModel(
            name='BoltJoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=250, verbose_name='соединяемый материал')),
                ('weight', models.FloatField(verbose_name='масса болтового соединения, кг')),
                ('bolt', models.ManyToManyField(related_name='boltjoint_bolt', to='parts_ordering.bolt', verbose_name='болт')),
                ('locknut', models.ManyToManyField(related_name='boltjoint_locknut', to='parts_ordering.nut', verbose_name='контргайка')),
                ('nut', models.ManyToManyField(related_name='boltjoint_nut', to='parts_ordering.nut', verbose_name='гайка')),
                ('bolt_washer', models.ManyToManyField(related_name='boltjoint_bolt_washer', to='parts_ordering.washer', verbose_name='шайба со стороны болта')),
                ('nut_washer', models.ManyToManyField(related_name='boltjoint_nut_washer', to='parts_ordering.washer', verbose_name='шайба со стороны гайки')),
            ],
        ),
    ]
