# Generated by Django 5.1.1 on 2024-09-11 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_ordering', '0003_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boltjoint',
            name='bolt',
        ),
        migrations.RemoveField(
            model_name='boltjoint',
            name='bolt_washer',
        ),
        migrations.RemoveField(
            model_name='boltjoint',
            name='locknut',
        ),
        migrations.RemoveField(
            model_name='boltjoint',
            name='nut',
        ),
        migrations.RemoveField(
            model_name='boltjoint',
            name='nut_washer',
        ),
        migrations.AddField(
            model_name='boltjoint',
            name='bolt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boltjoint_bolt', to='parts_ordering.bolt', verbose_name='болт'),
        ),
        migrations.AddField(
            model_name='boltjoint',
            name='bolt_washer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boltjoint_bolt_washer', to='parts_ordering.washer', verbose_name='шайба со стороны болта'),
        ),
        migrations.AddField(
            model_name='boltjoint',
            name='locknut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boltjoint_locknut', to='parts_ordering.nut', verbose_name='контргайка'),
        ),
        migrations.AddField(
            model_name='boltjoint',
            name='nut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boltjoint_nut', to='parts_ordering.nut', verbose_name='гайка'),
        ),
        migrations.AddField(
            model_name='boltjoint',
            name='nut_washer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boltjoint_nut_washer', to='parts_ordering.washer', verbose_name='шайба со стороны гайки'),
        ),
    ]
