# Generated by Django 5.1.1 on 2024-09-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_ordering', '0004_remove_boltjoint_bolt_remove_boltjoint_bolt_washer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boltjoint',
            name='cost',
            field=models.FloatField(default=1, editable=False, verbose_name='стоимость, руб'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boltjoint',
            name='weight',
            field=models.FloatField(editable=False, verbose_name='масса, кг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(editable=False, verbose_name='Стоимость, руб'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_items',
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(editable=False, verbose_name='масса заказа, кг'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='order_boltjoint', to='parts_ordering.boltjoint', verbose_name='состав заказа'),
        ),
    ]
