# Generated by Django 5.1.1 on 2024-09-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_ordering', '0005_boltjoint_cost_alter_boltjoint_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(editable=False, null=True, verbose_name='Стоимость, руб'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(null=True, related_name='order_boltjoint', to='parts_ordering.boltjoint', verbose_name='состав заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(editable=False, null=True, verbose_name='масса заказа, кг'),
        ),
    ]
