# Generated by Django 5.1.1 on 2024-09-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_ordering', '0007_alter_order_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(default=0, editable=False, verbose_name='Стоимость, руб'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0, editable=False, verbose_name='масса заказа, кг'),
        ),
    ]
